export const countriesByContinent = {
  EU: [
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Poland',
    'Netherlands',
    'Belgium',
    'Sweden',
    'Denmark',
    'Finland',
    'Austria',
    'Portugal',
    'Greece',
    'Ireland',
  ],
  ASIA: [
    'China',
    'Japan',
    'South Korea',
    'India',
    'Singapore',
    'Malaysia',
    'Thailand',
    'Vietnam',
    'Indonesia',
    'Philippines',
    'United Arab Emirates',
    'Saudi Arabia',
    'Israel',
  ],
  N_AMERICA: ['USA', 'Canada', 'Mexico'],
  S_AMERICA: ['Brazil', 'Argentina', 'Chile', 'Colombia', 'Peru'],
  AFRICA: ['South Africa', 'Egypt', 'Nigeria', 'Morocco', 'Kenya'],
  OCEANIA: ['Australia', 'New Zealand', 'Fiji'],
  REMOTE: ['Greenland', 'Iceland'],
};

export const distanceFactors = {
  'EU-EU': 1,
  'EU-ASIA': 1.3,
  'EU-N_AMERICA': 1.4,
  'EU-S_AMERICA': 1.5,
  'EU-AFRICA': 1.2,
  'EU-OCEANIA': 1.6,
  'GLOBAL-REMOTE': 1.6,
  'ASIA-ASIA': 1,
  'ASIA-N_AMERICA': 1.5,
  'N_AMERICA-S_AMERICA': 1.3,
  'N_AMERICA-OCEANIA': 1.7,
  'AFRICA-ASIA': 1.25,
};
